<?php require_once('Views/other/headerAlt.phtml') ?>
<div class="row justify-content-center">
    <div class="col-md-6 border-right justify-content-center">
        <div class="p-3 py-5">
            <div class="d-flex justify-content-center align-items-center mb-3">
                <h4 class="text-right">Create Listing</h4>
            </div>
            <div class="w-100 me-0">
            <form name="myform" id="myform" method="post" action="" class="form text-dark form-control was-validated"">
                <h6>Item name</h6>
                <div class="mb-3">
                    <input type="text" class="form-control" name="listingname" required maxlength="255">
                    <div class="invalid-feedback">Please provide a name</div>
                    <div class="valid-feedback">Looks Good!</div>
                </div>
                <h6>Listing description</h6>
                <div class="mb-3">
                    <textarea class="form-control" name="description" rows="3" required maxlength="255 "></textarea>
                    <div class="invalid-feedback">Please provide a description</div>
                    <div class="valid-feedback">Looks Good!</div>
                </div>
                <h6>Price</h6>
                <div class="mb-3">
                    <input type="number" class="form-control" name="price" step="0.01" required>
                    <div class="invalid-feedback">Please provide a price</div>
                    <div class="valid-feedback">Looks Good!</div>
                </div>
                <h6>Category</h6>
                <div class="mb-3">
                    <select class="select" form="myform" name="selectedOption">
                        <option value="Sports & Outdoors">Sports & Outdoors</option>
                        <option value="Clothing & Footwear">Clothing & Footwear</option>
                        <option value="Electronics & Computers">Electronics & Computers</option>
                        <option value="Baby & Children">Baby & Children</option>
                        <option value="Home & Garden">Home & Garden</option>
                        <option value="DIY & Tools">DIY & Tools</option>
                    </select>
                    <div class="invalid-feedback">Please select a category</div>
                    <div class="valid-feedback">Looks Good!</div>
                </div>
                <div class="mb-3">
                    <button type="submit" name="registerListings" class="btn btn-danger">Create</button>
                </div>
            </form>
            </div>
        </div>
    </div>
</div>
<?php require_once('Views/other/footer.phtml') ?>
