<?php require_once('Views/other/header.phtml');
require_once('Models/helperClass/Validator.php');?>

<?php
if(isset($_POST['SEARCH']))
{
    $validator = new Validator();
    $listingAPI->createCards($listingAPI->fetchSearchedListings($validator->validateInput($_POST['searchName']),
        $validator->validateInput($_POST['sellerName']), $validator->validateInput($_POST['minSearch']),
        $validator->validateInput($_POST['maxSearch']), $validator->validateInput($_POST['orderFilter']),
        $validator->validateInput($_POST['categoryFilter']), $validator->validateInput($_POST['locationFilter'])));
} else
{
    $listingAPI->createCards($listingAPI->fetchAllConfirmedListings());
}
?>



<script>
    function scanDiv(id){
        var name = document.getElementById("name"+id).innerText;
        var price = document.getElementById("price"+id).innerText;
        console.log(name + price);
    }
</script>


<?php require_once('Views/other/footer.phtml'); ?>
