<?php require_once('Views/other/header.phtml');?>

<table class="table table-dark table-striped table-responsive align-middle">
    <tr>
        <th scope="col">Listing ID</th>
        <th scope="col">Product Name</th>
        <th scope="col">Description</th>
        <th scope="col">Price</th>
        <th scope="col">Category</th>
        <th scope="col">Product Image</th>
        <th scope="col">Seller Details</th>
    </tr>
<?php require_once('Views/other/footer.phtml'); ?>
