<!-- Holds a bootstrap card that will contain login form -->
<?php require_once('Views/other/header.phtml'); ?>

<div class="card shadow text-center text-shrink border-red pt-5 resize">
    <div class="card-body p-8">
        <h1 class="card-title mb-3">Login</h1>
        <!-- Form starts here; includes validation form bootstrap -->
        <form method="POST" class="needs-validation" novalidate="" autocomplete="off">
            <div class="mb-3">
                <label class="text-muted" for="email">Username</label>
                <input id="email" type="email" class="form-control text-shrink border-red" name="email" value="" required autofocus>
                <div class="invalid-feedback">
                    Oh No! The email is invalid.
                </div>
            </div>

            <div class="mb-3">
                <label class="text-muted" for="password">Password</label>
                <input id="password" type="password" class="form-control text-shrink border-red" name="password" required>
                <div class="invalid-feedback">
                    Please enter a password...
                </div>
            </div>

            <button type="submit" class="btn btn-danger mb-3">Continue</button>
        </form>
    </div>
</div>

<?php require_once('Views/other/footer.phtml'); ?>