<?php

require_once('Views/other/headerAlt.phtml');

?>

    <div class="row justify-content-center">
        <div class="col-md-2 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" width="150px" src="<?php echo $_SESSION['profilePhoto'] ?>">
                <span class="font-weight-bold"><?php echo $_SESSION['fullName'] ?></span>
                <span class="text-muted"><?php echo $_SESSION['email'] ?></span><span></span>
            </div>
        </div>
        <div class="col-md-4 col-sm-12 border-right justify-content-center">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Profile Settings</h4>
                </div>
                <form action="<?php echo $phpSelf ?>" method="post" class="form-control user-form">
                <div class="row mt-3">
                    <div class="mt-1">
                        <label class="labels">Full Name</label>
                        <input type="text" name="changeName" class="form-control" placeholder="<?php echo $_SESSION['fullName'] ?>" value="">
                    </div>
                    <div class="mt-1">
                        <label class="labels">Mobile Number</label>
                        <input type="text" name="changeMobile" class="form-control" placeholder="<?php echo $_SESSION['number'] ?>" value="">
                    </div>
                    <div class="mt-1">
                        <label class="labels">New Password</label>
                        <input type="password" name="changePass" class="form-control" placeholder="Enter New Password" value="">
                    </div>
                    <div class="mt-1">
                        <label class="labels">Confirm New Password</label>
                        <input type="password" name="changePassConfirm" class="form-control" placeholder="Enter New Password" value="">
                    </div>
                    <div class="mt-3">
                        <button class="btn btn-danger profile-button" type="submit" name="changeProfile">Save Profile</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 border-right">
            <div class="d-flex justify-content-center mb-3">
                <h4 class="text-left">My Listings</h4>
            </div>
            <div id="profile-table">
            <table class="table table-light table-striped table-responsive">
                <tr class="">
                    <th scope="col">Listing ID</th>
                    <th scope="col">Product Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Price</th>
                    <th scope="col">Category</th>
                    <th scope="col">Product Image</th>
                    <th scope="col">Edit/Delete</th>
                </tr>
            </div>
        </div>
    </div>
</div>


<?php require_once('Views/other/footer.phtml'); ?>


