<?php

require_once('Views/other/headerAlt.phtml');

?>
<div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" width="150px" src="<?php echo $_SESSION['profilePhoto'] ?>">
                <span class="font-weight-bold"><?php echo $_SESSION['fullName'] ?></span>
                <span class="text-muted"><?php echo $_SESSION['email'] ?></span><span></span>
            </div>
        </div>
        <div class="col-md-5 border-right">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Profile Settings</h4>
                </div>
                <div class="row mt-3">
                    <div class="col-md-12"><label class="labels">Full Name</label><input type="text" class="form-control" placeholder="<?php echo $_SESSION['fullName'] ?>" value=""></div>
                    <div class="col-md-12"><label class="labels">Mobile Number</label><input type="text" class="form-control" placeholder="<?php echo $_SESSION['number'] ?>" value=""></div>
                    <div class="col-md-12"><label class="labels">New Password</label><input type="text" class="form-control" placeholder="Enter New Password" value=""></div>
                    <div class="col-md-12"><label class="labels">Confirm New Password</label><input type="text" class="form-control" placeholder="Enter New Password" value=""></div>
                </div>
                <div class="mt-3"><button class="btn btn-danger profile-button" type="button">Save Profile</button></div>
            </div>
        </div>
    </div>
</div>
<table class="table table-light table-striped table-responsive border">
        <tr>
            <th scope="col">Listing ID</th>
            <th scope="col">Product Name</th>
            <th scope="col">Description</th>
            <th scope="col">Price</th>
            <th scope="col">Category</th>
            <th scope="col">Product Image</th>
            <th scope="col">Edit/Delete</th>
        </tr>
<?php require_once('Views/other/footer.phtml'); ?>


