</section>
</div>
</div>
</main>

<!-- Footer Content starts here -->
<footer class="footer fixed-bottom mt-auto py-3 bg-light">
    <div class="container text-center">
            <ul class = "list-inline">
                <li class = "list-inline-item">
                      <a>Accessibility</a>
                </li>
                <li class = "list-inline-item">
                    <a>Cookies</a>
                </li>
                <li class = "list-inline-item">
                    <a>Privacy policy</a>
                </li>
                <li class = "list-inline-item">
                    <a>Disclosures</a>
                </li>
                <li class = "list-inline-item">
                    <a>Risk warnings</a>
                </li>
                <li class = "list-inline-item">
                    <a>Website use</a>
                </li>
                <li class = "list-inline-item">
                    <a>Terms and conditions</a>
                </li>
                <li class = "list-inline-item">
                    <a>Anti-slavery statement</a>
                </li>
            </ul>
    </div>
</footer>


<!-- Bootstrap core JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</body>
</html>
