<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="Marketplace">
    <meta name="author" content="Group 2">

    <!-- Importing Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- Importing CSS file(s) -->
    <link href="/css/main.css" rel="stylesheet">
    <!-- Importing Favicon file -->
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico">

    <title>Marketplace - <?php echo $view->pageTitle; ?></title>

</head>

<body class="d-flex flex-column h-100 pt-auto">

<header>
    <nav class="navbar navbar-expand-md navbar-light bg-light fixed-top space border-bottom">
        <div class="container-fluid">
            <a href="index.php" class="navbar-brand">
                <img class ="logo"  alt="Company Logo" width="200px" height="64px" src="images/company_logo.png"/>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0 justify-content-end">
                    <li class="nav-item nav-space">
                        <a class="nav-link text-dark" href="#">Home</a>
                    </li>
                    <li class="nav-item nav-space">
                        <a class="nav-link text-dark" href="#" >My Listings</a>
                    </li>
                    <li class="nav-item nav-space">
                        <a class="nav-link text-dark" href="#" >Create Listing</a>
                    </li>

                    <li class="nav-item nav-space">
                        <a class="nav-link text-dark" href="#" >My Profile</a>
                    </li>

                    <li class="nav-item nav-space">
                        <form action="index.php" method="POST">
                            <button type="submit" name="LOGOUT" class="btn btn-danger">Logout</button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<!-- Begin page content -->
<main class="flex-shrink-0 ">
    <div class="container-fluid">
        <div class="row">
            <div id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="position-sticky pt-3 sidebar-sticky">
                    <div class="nav flex-column ms-3">
                        <form>
                            <h5>Filter listings</h5>
                            <h6>Item name</h6>
                            <div class="row mb-3 col-12">
                                <input type="text" class="form-control w-100" id="searchName">
                            </div>
                            <h6>Seller</h6>
                            <div class="row mb-3 col-12">
                                <input type="text" class="form-control w-100" id="sellerName">
                            </div>
                            <h6>Category</h6>
                            <div class="row mb-3 col-12">
                                <select class="select col-12" id="categoryFilter">
                                    <option value="0">All categories</option>
                                    <option value="1">Baby & Children</option>
                                    <option value="2">Clothing & Footwear</option>
                                    <option value="3">DIY & Tools</option>
                                    <option value="4">Electronics & Computers</option>
                                    <option value="5">Home & Garden</option>
                                    <option value="6">Jewellery & Accessories</option>
                                    <option value="7">Sports & Outdoors</option>
                                </select>
                            </div>
                            <h6>Seller Location</h6>
                            <div class="row mb-3 col-12 w-100">
                                <select class="select col-12" id="locationFilter">
                                    <option value="0">All locations</option>
                                    <option value="1">Bristol</option>
                                    <option value="2">London</option>
                                    <option value="3">Manchester</option>
                                </select>
                            </div>
                            <h6>Price range</h6>
                            <div class="row mb-3 col-12">
                                <div class="col-6">
                                    <label for="minSearch">Minimum</label>
                                    <input type="text" class="form-control w-75" id="minSearch" value="0">
                                </div>
                                <div class="col-6">
                                    <label for="maxSearch">Maximum</label>
                                    <input type="text" class="form-control w-75" id="maxSearch">
                                </div>
                            </div>
                            <h5>Order by</h5>
                            <div class="row mb-3 col-12">
                                <select class="select col-12" id="orderFilter">
                                    <option value="0">None</option>
                                    <option value="1">Listing name (A-Z)</option>
                                    <option value="2">Listing name (Z-A)</option>
                                    <option value="3">Cost (Low-High)</option>
                                    <option value="4">Cost (High-Low)</option>
                                    <option value="5">Listing age (Newest-Oldest)</option>
                                    <option value="6">Listing age (Oldest-Newest)</option>
                                </select>
                            </div>
                            <button type="submit" name="SEARCH" class="btn btn-danger">Search</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <main class="col-md-9 ms-sm-auto col-lg-10 py-0 text-center">

