<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="Marketplace">
    <meta name="author" content="Group 2">

    <!-- Importing Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- Importing CSS file(s) -->
    <link href="/css/main.css" rel="stylesheet">
    <!-- Importing Favicon file -->
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico">

    <title>Marketplace - <?php echo $view->pageTitle; ?></title>

</head>

<body class="d-flex flex-column h-100">

<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark space">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Fixed navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item nav-space">
                        <a class="nav-link active " aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item nav-space">
                        <a class="nav-link " href="#" >My Listings</a>
                    </li>
                    <li class="nav-item nav-space">
                        <a class="nav-link " href="#" >Create Listing</a>
                    </li>

                    <li class="nav-item nav-space">
                        <a class="nav-link  href="#" >My Profile</a>
                    </li>

                    <li class="nav-item nav-space">
                        <a class="nav-link  href="#" >Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<!-- Begin page content -->
<main class="flex-shrink-0">

    <div class="container">

        <div class="row">
            <section id="content" class="col-xs-6 col-sm-9 col-md-10">
