<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="Marketplace">
    <meta name="author" content="Group 2">

    <!-- Importing Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- Importing CSS file(s) -->
    <link href="/css/main.css" rel="stylesheet">
    <!-- Importing Favicon file -->
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico">

    <title>Marketplace - <?php echo $view->pageTitle; ?></title>

</head>


<body class="d-flex flex-column h-100">

<nav class="d-flex flex-wrap justify-content-center py-3 mb-4">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <img class ="logo"  alt="Company Logo" width="200px" height="64px" src="images/company_logo.png"/>
    </a>

    <ul class="nav nav-pills">
        <li class="nav-item"><a href="#" class="nav-link active" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Example</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Example</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Example</a></li>
    </ul>
</nav>


<!-- Begin page content -->
<main class="pt-5">

    <div class="container-sm pt-5">

        <div class="row">
            <section id="content">
